using edu4.Domain.Common;
using edu4.Domain.Users;

namespace edu4.Domain.Projects;
public class Position : AbstractEntity
{
    public DateTime DatePosted { get; private set; }
    public string Name { get; private set; }
    public string Description { get; private set; }
    public Hat Requirements { get; }


    public Position(
        DateTime datePosted,
        string name,
        string description,
        Hat requirements)
    {
        Id = Guid.NewGuid();    // positions are nested objects; ids won't be generated by MongoDB driver
        DatePosted = datePosted;
        Name = name;
        Description = description;
        Requirements = requirements;
    }
}
