using Peer.Domain.Common;
using Peer.Domain.Contributors;

namespace Peer.Domain.Projects;
public class Position : AbstractEntity
{
    public DateTime DatePosted { get; }
    public string Name { get; private set; }
    public string Description { get; private set; }
    public Hat Requirements { get; }
    public bool Open { get; private set; }

    public Position(
        string name,
        string description,
        Hat requirements)
    {
        Id = Guid.NewGuid();    // positions are nested objects; ids won't be generated by MongoDB driver
        DatePosted = DateTime.UtcNow;
        Name = name;
        Description = description;
        Requirements = requirements;
        Open = true;
    }

    public bool IsRecommendedFor(Contributor user) => user.Hats.Any(h => h.Fits(Requirements));
    internal void Close()
    {
        if (!Open)
        {
            throw new InvalidOperationException("Only an open position can be closed");
        }

        Open = false;
    }
}
